### ISSUE TITLE
ToDo's Patrick

### ISSUE THREAD

**Issue by beyersdp** [beyersdp/eHealth-Project#11]
Bitte folgende Punkte entsprechend der Reihenfolge abarbeiten und im jeweiligen Commit referenzieren.

**Direkte Bearbeitung**
- [x] Mainpage/Einsatz-Chronik erweitere Informationen in Allgemeine Lage ändern

**Wichtige Punkte**
- [x] Führungsposition mit Kerndaten gemeinsam speichern und rendern. Dabei in der Historie den Einsatzbeginn als Attribut speichern
- [x] Mainpage/Einsatz-Chronik rendern
- [x] Gesamtdoku rendern und DB zurücksetzen
- [x] Einsatz abschließen implementieren (eigenes Attribut, beim Rendern beachten)
- [x] Einsatz bearbeiten implementieren
- [x] Status visualisieren mittels jeweiliger roter Linien [wenn vorhanden]
- [x] Einsatz mit Standort auf der Karte speichern (Abhängigkeiten zu eingeteilten Rettungskräften)
- [x] Wenn Einsatz beendet wird alle Schichten aller Kräfte auch beenden zu diesem Zeitpunkt. Auf diese Funktion in der Alert-Message vor dem Beenden hinweisen
- [x] Auslieferbarkeit herstellen mit lokalem node.js und lokaler MongoDB Datenbank

**Punkte mit niedriger Priorität**
- [x] Position einer Markers automatisiert und asynchron setzen
- [ ] Funktion für Mülleimer neben Rettungskräfte-Zuteilungen [wenn vorhanden]
- [ ] Aktuellen Layer der Map speichern und dynamisch rendern
- [ ] Vergangene Zeit zu einem Einsatz kontinuierlich anzeigen
- [ ] Dataset mit HiOrgs anbieten
