### ISSUE TITLE
ToDo's Anita

### ISSUE THREAD

**Issue by beyersdp** [beyersdp/eHealth-Project#12]
Bitte folgende Punkte entsprechend der Reihenfolge abarbeiten und im jeweiligen Commit referenzieren.

**Direkte Bearbeitung**
- [x] Mainpage/Kerndaten eingeben: Inputfeld für Risikoeinstufung (Freitext einzeilig)
- [x] Mainpage/Notizen: Kategorien in blauer Zeile entfernen und nur Notiz-Symbol darstellen
- [x] Mainpage/Einsatz-Chronik: Anzahl an Verletzen entfernen
- [x] Gesamtdoku: zu den Kerndaten neben dem Datum noch Beginn und Ende des Gesamteinsatzes
- [x] Gesamtdoku: aus Rettungsmitteln und Posten Besatzung und Position entfernen
- [x] Gesamtdoku: aus Rettungskräften Posten und Rettungsmittel entfernen und Funkruf in Auflistung, nicht in den Überschriftbalken
- [x] Gesamtdoku: NavBar entfernen

**Wichtige Punkte**
- [x] Mainpage/Kerndaten visualisieren: mehr Felder auf die rechte Seite
- [x] Mainpage/Einsatz anzeigen (links): abhängig vom Status des Einsatzes den Button zum Meldebild rot umranden (1-2 rot durchgehend, 3-5 rot gestrichelt, 6 keine Umrandung). Dies auch in der Einsatz-Chronologie umsetzen. Visualisierung an drei Beispiel-Einsätzen direkt im Mainpage-Code
- [x] Mainpage/Einsatz anzeigen (links): Icon für Status des Einsatzes finden (erste Zeile)
- [x] Gesamtdoku: Für Rettungsmittel, Posten und Rettungskräfte noch Dienstbeginn und Dienstende hinzufügen (vgl. erste Integration)
- [x] Gesamtdoku: Neues Feld für die beteiligten Führungskräfte in das Design integrieren
- [x] Mainpage: Shortcuts für alle Funktionen, sowie Notiz schreiben außer Führungsposition wählen. Möglicherweise EventListener und clickOn() Funktion verwenden. Definierte Shortcuts in das DropDownMenü der NavBar schreiben
- [x] Gesamtdoku: PDF erzeugen / Drucken Button aktivieren (Funktion googlen oder Aufruf von STRG+P)
- [x] Mainpage/Funkspruch-Chronik: Sender, Empfänger, Führungskraft in eine Zeile
- [x] Mainpage: Hilfe-Button mit Kurzbeschreibungen/kleines Tutorial
- [x] Mainpage/Führungsposition ändern Popup: X zum Schließen des Fensters entfernen

**Punkte mit niedriger Priorität**
- [x] Einsatz-Marker auf der Karte rot verschönern [wenn verfügbar]
- [x] Login: Infotexte anbieten
- [x] Mainpage: Bei jeder Zuordnung von Kräften Mülleimericon rechts neben das Input-Feld
- [x] Mainpage: Ausrufezeichen für rechten Reload-Button anzeigen, wenn Seite neugeladen werden soll (vgl. Funktion in historie.js)
- [x] Mainpage/Notizen eingeben: Speichern-Button rechts neben Inputfeld (vorhandenes Form-Element verwenden)
